global:
    username: m.housh
    password: Mjh063079

hhe/dev:
    index: /m.housh/dev
    host: devpi.hhe.lan

local:
    host: devpi-server
    port: 3141
    scheme: http
    index: /root/public
    username: root
    password: Mjh063079

